[phases.setup]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
]

[phases.build]
cmds = [
    "python3 manage.py collectstatic --noinput",
]

[start]
cmd = "python manage.py migrate && gunicorn weather_project.wsgi:application --bind 0.0.0.0:$PORT"