[build]
language = "python"
version = "3.10"  # Use a stable, widely supported version

[phases.setup]
cmds = [
    "python --version",  # Debug: Check Python version
    "which python",      # Debug: Check Python location
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt",
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
]

[start]
cmd = "python manage.py migrate && gunicorn weather_project.wsgi:application --bind 0.0.0.0:$PORT"